{
    'name': 'Hospital Management',
    'version': '12.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Module for managing the hospitals',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Ogulgerek B',
    'website': 'odoomates.com',
    'live_test_url': 'https://www.youtube.com/watch?v=BDepk0LhVuI&list=PLqRRLx0cl0hoJhjFWkFYowveq2Zn55dhM&index=1',
    'depends': ['sale', 'mail', 'report_xlsx'],
    'demo': [],
    'data': [
        'patient.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
